autopkg/jleggat-recipes

AdobeShockwavePlayer/AdobeShockwavePlayer.munki.recipe

I added a PkgPayloadUnpacker to get the weird version information from
the DirectorShockwave.plugin into an installs item for Munki.

Add installs pkginfo for Adobe's versioning issues

---

Git/Git.download.recipe

SF must have changed their links to be just relative, so we need to add in the host to the URL.

Update url argument to URLDownloader

---

Wireshark/Wireshark.download.recipe

* Cleaned up download URL regex in `URLTextSearch` processor
* Removed prepended "https://www.wireshark.org" in `url` var in the
`URLDownloader` processor, since full URL present in regex match in
previous processor step.

Fixup for download URL regex

---

Wireshark/Wireshark.download.recipe
Wireshark/Wireshark.munki.recipe

The receipts and their version info from Wireshark installer package are not correct. Corrected this by extracting Wireshark package contents and creating an installs item for Munki. Also added a CodeSignatureVerifier processor to the download recipe.

Improvements for Wireshark recipes

---

Git/Git.download.recipe

Phew-see what you think about this one.
I noticed that it must be up to the maintainer to decide what is "latest", and the latest version available in the files section is definitely not it.
The change to the regex should now find the first download link in the files list, bypassing the "latest" version that was specified before (as a path, rather than a full URL-this means I had to change the string catting in the urldownloader as well). 
Of course, there's no guarantee that the latest version will actually be at the top of the list; I've seen other projects (Nethack maybe?) where it is actually sorted by date added, which makes things more complicated. If need be, it's possible to just grab all of the download links and write a processor to do version comparisons, but for right now this …

Fix Git recipe to get current version.

---

Git/Git.download.recipe

The https version of the download site works.
Unfortunately, no way to do code signature verification:
```pkgutil --check-signature /Volumes/Git\ 2.8.1\ Mavericks\ Intel\ Universal/git-2.8.1-intel-universal-mavericks.pkg 
Package "git-2.8.1-intel-universal-mavericks.pkg":
Status: no signature```

https and note about code sig ver

---

nvAlt/nvALT.download.recipe

nvALT is still using version 1 signature, so we can't run code signature verification on the download recipe. This just adds a note into the description.
```
codesign --display -r- --deep -v /Applications/nvALT.app 
Executable=/Applications/nvALT.app/Contents/MacOS/nvALT
Identifier=net.elasticthreads.nv
Format=app bundle with Mach-O universal (i386 x86_64)
CodeDirectory v=20100 size=5110 flags=0x0(none) hashes=247+5 location=embedded
Signature size=8514
Timestamp=Jun 8, 2013, 12:24:14 PM
Info.plist entries=35
TeamIdentifier=not set
Sealed Resources version=1 rules=4 files=244
designated => anchor apple generic and identifier "net.elasticthreads.nv" and (certificate leaf[field.1.2.840.113635.100.6.1.9] /* exists */ or certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and …
```

Code sig ver note for nvALT

---

EasyFind/EasyFind.download.recipe

Added code signature verification for EasyFind. Also converted spaces to tabs (only for consistency) 😆 
```
$ autopkg run EasyFind.download -v
Processing EasyFind.download...
WARNING: EasyFind.download is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
URLTextSearcher: Found matching text (match): https://s3.amazonaws.com/DTWebsiteSupport/download/freeware/easyfind/4.9.3/EasyFind.app.zip
URLDownloader
URLDownloader: Storing new Last-Modified header: Thu, 17 Jul 2014 06:23:43 GMT
URLDownloader: Storing new ETag header: "38c811eb79b5ff3b8b74c0f4c4f16ad5"
URLDownloader: Downloaded /Users/cwhits/Library/AutoPkg/Cache/com.github.jleggat.EasyFind.download/downloads/EasyFind.zip
EndOfCheckPhase
Unarchiver
Unarchiver: Guessed archive format 'zip' …
```

[EasyFind] Add CodeSignatureVerification

---

PostgresApp/PostgresApp.download.recipe
PostgresApp/PostgresApp.install.recipe
PostgresApp/PostgresApp.munki.recipe

Postgres.app is now distributed in disk images instead of zip files. They also now provide a Sparkle feed which may be more reliable than scraping the downloads page. Fixes #51.

Switch to Sparkle feed and .dmg files for PostgresApp download

---

Fetch/Fetch.download.recipe

Overnight our build failed:
> The following recipes failed:
>     Fetch.munki.recipe
>        Error in local.munki.Fetch: Processor: URLTextSearcher: Error: No match found on URL: https://www.fetchsoftworks.com/fetch/download/Fetch_5.7.6.dmg?direct=1
Running throught the steps by hand, it seems that the download link on
the front page now redirects and downloads the .dmg:
$ curl  --dump-header - https://fetchsoftworks.com/fetch/download/Fetch_5.7.6.dmg?direct=1
HTTP/1.1 301 Moved Permanently
Date: Fri, 31 Mar 2017 06:17:20 GMT
Server: Apache/2.4.25
X-Kitty: Meow!
X-test: 1
Location: http://getfetch.com/Fetch_5.7.6.dmg
Content-Length: 0
Content-Type: text/html
so this patch removes the now unnecesary URLTextSearcher  processor

Fetch download location seems to have changed

---

Fetch/Fetch.download.recipe

Overnight the Fetch download seems to have changed to download HTML, rather than the DMG:
$ file /srv/autopkg/Cache/local.munki.Fetch/downloads/Fetch.d mg
/srv/autopkg/Cache/local.munki.Fetch/downloads/Fetch.dmg: HTML document text
This is because the page age
http://fetchsoftworks.com/fetch/download/Fetch_5.7.6.dmg
is now HTML which automagically starts the download in my browser,
providing a direct download link too.
This PR reverses the earlier pull request, which means that the recipe now checks
the intermediate page for the new link.

Fetch download changes

---

Fetch/Fetch.download.recipe

Build the %version% substitution value from URLTextSearcher.
This allows us to remove two processor steps between the download and pkg recipes.
Also, since Fetch has two different version strings that can't be easily compared (v5.7.7 vs v5.7.1795), this requires an EA to pull a version string to compare in the JSS.
Getting the version string from URLTextSearcher (which matches the jss_inventory_app <-> version) and using it as criteria in a Smart Group Template removes the need for an EA.

Fetch - Build %version% from URLTextSearcher

---

PostgresApp/PostgresApp.munki.recipe

Over the weekend PostgresApp stopped building for us with the error:
```
Error in local.munki.PostgresApp:
Processor: DmgCreator:
Error: creation of /srv/autopkg/Cache/local.munki.PostgresApp/PostgresApp.dmg failed:
hdiutil: create failed - error -5341
```
According to autopkg/autopkg#87 one work around for this is to add the
-megabytes parameter to DmgCreator; this patch does just that - adding
a value of 250 M (this is an estimate based on rounding up the current size
of 189M).

Add dmg_megabytes to PostgresApp.munki.recipe

---

Fetch/Fetch.download.recipe

switching to `%match%` from `%url%` fixes an issue where the returned
URL generates a 404.

Fixes issue with Download recipe

---

Fetch/Fetch.pkg.recipe

This will keep the "Version" variable using the release number pulled from the website.
i.e. `5.7.7` instead of `5.7.1795`

Change the "Version" String to the Web Release

---

Fetch/Fetch.pkg.recipe
LightPaper/LightPaper.install.recipe
LightPaper/LightPaper.pkg.recipe
MacDown/MacDown.install.recipe
MacDown/MacDown.pkg.recipe

Because variables can be overridden, it's a good idea to make sure that the recipe will still work even if a non-default variables used. One issue that would prevent recipes from running is using a `NAME` variable in paths that should be hard-coded (e.g. `/Applications/Foo.app`).
This PR removes the `NAME` variable from all file paths and replaces it with the actual app name, which should make the recipe more resilient for overrides.

Remove NAME variable from app paths

---

Webmin/Webmin.munki.recipe

According to the Munki wiki, the possible values for `uninstall_method` include one of:
- removepackages
- remove_copied_items
- remove_app
- uninstall_script
- remove_profile
- one of the "Adobe*" removal methods
- **the absolute path to a local script**
https://github.com/munki/munki/wiki/Supported-Pkginfo-Keys
So there's no need to set `uninstall_script` as the method; just use the path to the script itself.

Fix uninstall method for Webmin

---

PostgresApp/PostgresApp.download.recipe

Howdy!
it seems like they started using a new sparklefeed. This should fix it and make it easier to override later on.

it seems like the latest updates are using a new sparkle feed

---

AdobeShockwavePlayer/AdobeShockwaveVersioner.py
Fetch/FetchScriptsPath.py
Monit/MonitVersioner.py
TestDisk/TestDiskVersioner.py

In order to make your processors more compatible with AutoPkg running in Python 3, I've applied a few adjustments suggested by `python-modernize`, `pylint --py3k`, and `pylint` in general.
More adjustments may need to be made manually later, but this should catch the low-hanging fruit right now.

Basic python3 compatibility

---

MacVim/MacVim.munki.recipe
MacVim/MacVim.pkg.recipe
MacVim/MacVimpkg.munki.recipe

My apologies, when I submitted the PR I did not test all the way through to the munki recipe ...
This may be more my own opinion, but generally for munki recipes I prefer to leave drag-and-drop apps alone and just import them.  If there are any binaries or things within the app that need to be copied, symlinked, etc., that can be easily handled via a postinstall script.  As it is now, your munki recipe leans on the pkg recipe, which assumes that an admin would want to copy out and symlink those binaries.
To achieve both ends, I made the following changes:
**MacVim.pkg.recipe**
- Remove extraneous Unarchiver processor
- Replace Versioner with PlistReader.  Since you're building a PKG when importing into munki you lose the LSMinimumSystemVersion available if you just import the pkg as is. …

More MacVim updates

---

RagingMenace/MenuMeters.pkg.recipe

`pkgname` is [intended](https://github.com/autopkg/autopkg/blob/e36d5cba2823dbdfcb69a41a38b1aef9fb76121c/Code/autopkgserver/autopkgserver#L47) to be in the `pkg_request` dictionary, not as a standalone argument for [PkgCreator](https://github.com/autopkg/autopkg/wiki/Processor-PkgCreator).

Adjust PkgCreator arguments

---

Wireshark/Wireshark.munki.recipe

Since Wireshark is being installed from a pkg, Munki does not automatically infer blocking applications.

Add blocking app for Wireshark

---

Fetch/Fetch.munki.recipe

Since Fetch is being installed from a pkg, Munki does not automatically infer blocking applications.

Add blocking app for Fetch

---

Git/Git.download.recipe

The recipe started to fail with the old regex. Because the name of the `MAJOR_OS_VERSION` has not changed for 6 years so that is probably fine to hard code it into the regex. Making the regex more specific should allow it to be more consistent while the flexibility for new versions is still there.
Output for `autopkg run -vv com.github.jleggat.Git.download`:
```
Processing com.github.jleggat.Git.download...
WARNING: com.github.jleggat.Git.download is missing trust info and FAIL_RECIPES_WITHOUT_TRUST_INFO is not set. Proceeding...
URLTextSearcher
{'Input': {'re_pattern': 'href="(https:\\/\\/sourceforge.net\\/projects\\/git-osx-installer\\/files\\/git-[\\.\\d]+-intel-universal-mavericks\\.dmg\\/download)"',
'url': 'https://sourceforge.net/projects/git-osx-installer/files/'}} …
```

update regex for Git recipe

---

Git/Git.download.recipe

The change made in Pull request #102 was reverted by #103 and now the download fails again.

revert git search pattern change

---

AdobeShockwavePlayer/AdobeShockwaveVersioner.py
Fetch/FetchScriptsPath.py
Monit/MonitVersioner.py
TestDisk/TestDiskVersioner.py

As of macOS Monterey 12.3, the version of Python 2 that shipped with macOS located at `/usr/bin/python` [has been removed](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes). More context can be found in some posts from Mac admins at the beginning of 2022, aggregated [here](https://scriptingosx.com/2022/03/macos-monterey-12-3-removes-python-2-link-collection/).
Since [version 2.0.2](https://github.com/autopkg/autopkg/releases/tag/v2.0.2), AutoPkg's installer has included its own Python 3 framework, symlinked from `/usr/local/autopkg/python`. This pull request adjusts the "shebang" interpreter paths of processors to replace `/usr/bin/env python` with the AutoPkg Python 3 path.
NOTE: Because AutoPkg processors are imported as modules by AutoPkg and not …

Update Python path in processors to reflect changes in macOS 12.3+

---

MunkiAdmin/MunkiAdmin.download.recipe

Similar to #109
Also retabbed the file to have consistent tabs (had some softtabs/spaces in it)
Example run:
```
autopkg  run -vv --ignore-parent-trust-verification-errors  MunkiAdmin.munki.recipe
Processing MunkiAdmin.munki.recipe...
GitHubReleasesInfoProvider
{'Input': {'asset_regex': 'MunkiAdmin.*.dmg',
'github_repo': 'hjuutilainen/munkiadmin',
'include_prereleases': ''}}
GitHubReleasesInfoProvider: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
GitHubReleasesInfoProvider: No value supplied for GITHUB_URL, setting default value of: https://api.github.com
GitHubReleasesInfoProvider: No value supplied for GITHUB_TOKEN_PATH, setting default value of: ~/.autopkg_gh_token
GitHubReleasesInfoProvider: Matched regex 'MunkiAdmin.*.dmg' among asset(s): …
```

Use GitHubReleasesInfoProvider for MunkiAdmin

---

Pandoc/Pandoc.download.recipe

I think github changed the releaes html template and pandoc fails to download. Used this moment to upgrade from generic URLDownloader code to GithubReleaseInfoProvider.
Example run:
```
autopkg  run -vv --ignore-parent-trust-verification-errors Pandoc.munki.recipe 
Processing Pandoc.munki.recipe...
GitHubReleasesInfoProvider
{'Input': {'asset_regex': 'pandoc-.*-macOS.pkg',
'github_repo': 'jgm/pandoc',
'include_prereleases': ''}}
GitHubReleasesInfoProvider: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
GitHubReleasesInfoProvider: No value supplied for GITHUB_URL, setting default value of: https://api.github.com
GitHubReleasesInfoProvider: No value supplied for GITHUB_TOKEN_PATH, setting default value of: ~/.autopkg_gh_token
GitHubReleasesInfoProvider: Matched …
```

Use GitHubReleasesInfoProvider for Pandoc

---

Pandoc/Pandoc.download.recipe
Pandoc/Pandoc.munki.recipe

Currently, pandoc breaks, because the github asset regex will prefer the arm64 package. This PR addes the ARCH input, so:
+ the default is restored (downloading x86_64)
+ users can create a second override with ARCH set to arm64

Add ARCH input for pandoc to support arm64

---

PostgresApp/PostgresApp.download.recipe

The release URL changed from
https://postgresapp.com/sparkle/updates_10_11_12_13_14_15.xml to
https://postgresapp.com/sparkle/updates_11_12_13_14_15_16.xml to include v16 and remove v10

Release URL changed

---

LightPaper/LightPaper.download.recipe

This PR deprecates the LightPaper recipes, since the website that hosted the software is no longer online.

Deprecate LightPaper recipes
